# Generated by Django 4.1.3 on 2023-01-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangecode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='school_id',
            new_name='school',
        ),
    ]
