# Generated by Django 4.1.5 on 2023-01-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangecode', '0002_rename_area_id_teacher_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='area',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='exchangecode.area', verbose_name='所属区域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='exchangecode.school', verbose_name='所属分校'),
            preserve_default=False,
        ),
    ]
